server:
  port: 8080
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/genshin_chat?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: 123456
  servlet:
    multipart:
      max-file-size: 500MB
      max-request-size: 500MB
  http:
    multipart:
      max-file-size: 500MB
      max-request-size: 500MB
  redis:
    host: 127.0.0.1
    port: 6379
    password:
    database: 0
  cache:
    redis:
      time-to-live: 1800000 #设置缓存数据的过期时间
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: ASSIGN_ID
knife4j:
  enable: true
  openapi:
    title: 聊天管理接口
    description: "聊天管理接口"
    email: 114514@xbz
    concat: wjh
    url: http://vvvv.com
    version: v1.0.0
    group:
      default:
        group-name: default
        api-rule: package
        api-rule-resources:
          - com.homework.genshinchat.controller